### ISSUE TITLE
Feature: Hide files and just have package names

### ISSUE THREAD

**Issue by markmghali** [Nyaran/myjdownloader-card#11]
Awesome Card thank you! Anyway to hide files and just have the packages to make the card shorter? or collapse-able like it is in jdownloader?

**Comment by Nyaran** [comment]
Hi! thanks for your words :)

I want to improve the card with some features, like collapsable packages, but  I didn't have enought free time for it. Anyway, an option to show only packages/links, should be easy to add, I will try to add it along this week.
