### ISSUE TITLE
Card does not show the package

### ISSUE THREAD

**Issue by nightfever77** [Nyaran/myjdownloader-card#12]
Card does not show the package. Any idea? 
![image](https://user-images.githubusercontent.com/73058571/197997293-2c01a872-e02f-47e8-9351-2da743b7682c.png)

**Comment by nightfever77** [comment]
The integrations packages sensor was disabled by default. After activation the card is completely empty now. ???

**Comment by Nyaran** [comment]
Hi,

are you sure that you enabled two needed sensors? The sensors ends with "_links" and "_packages"
