### ISSUE TITLE
Card is not showing what it is downloading

### ISSUE THREAD

**Issue by Hadatko** [Nyaran/myjdownloader-card#4]
Hi, very nice service. But i have bug bellow.
![image](https://user-images.githubusercontent.com/13130700/193040457-484f864f-7096-4d69-bbac-2b61e4d98fef.png)
When i ask sensor in node red it looks working:
![image](https://user-images.githubusercontent.com/13130700/193042023-a675cd99-5027-4f46-bb8e-ff226b999ad5.png)

**Comment by Nyaran** [comment]
Hi,

have you enabled also the `packages` sensor? In your case it should be `sensor.jdownloader_jdownloader_pi_packages`

**Comment by Hadatko** [comment]
No it was forbidden. Sorry for bothering. Any plan to add feature to add link from HA?
Thank you very much
