### ISSUE TITLE
Instance selector

### ISSUE THREAD

**Issue by Turiko313** [Nyaran/myjdownloader-card#52]
Good morning.  Great work, the visual is perfect for me 👍.
 I just have one problem, I have a myjdownloader account which runs 3 instances.  These are 3 instances with different names.
 In the map configuration, instances selection displays 3 times the same.  I can't get the 3 names.
 If I make 3 cards, I have the 3 names that are recognized.
 Can you help me?  THANKS

 I apologize for the English, I use a translator

**Comment by Nyaran** [comment]
Hi,

thanks for your report. As you said, there are a couple of bugs on instances selector.

I'm working on it

Pd. If you feel comfortable writing in Spanish, feel free to use it, is my native language

**Comment by Nyaran** [comment]
Fixed! Please, update to v1.3.0

**Comment by Turiko313** [comment]
Problem solved !  🥳 

For Spanish, it would be worse, I'm French.  
If ever, I will take this opportunity to add some feedback.  The map configuration window is rather unstable.  Nothing serious, you just have to remember to save the modifications one by one.  The instability may be caused by my installation, I don't know.  
Another point, the 'latest release' link on the hacs page is dead.  

Thank you again for your work and your responsiveness.  Best wishes

**Comment by Nyaran** [comment]
Thank you for your comments, it is greatly appreciated.

I don't know what you mean by map settings, can you provide more information or a screenshot? If so, do so by creating another ticket.

About the broken link, you mean the link to download the latest version with the manual method, without using hacs, right? I don't see any other broken links. If that's what you mean, thanks for noticing, I'm fixing it right now (#55), if not, please let me know what the link is.
