### ISSUE TITLE
DATA_RATE_MEGABYTES_PER_SECOND deprecated

### ISSUE THREAD

**Issue by ojaksch** [Nyaran/myjdownloader-card#66]
The log of my HA (at least 2024.1.0) is throwing the following message

```2024-01-05 11:59:15.493 WARNING (MainThread) [homeassistant.const] DATA_RATE_MEGABYTES_PER_SECOND was used from myjdownloader, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.MEGABYTES_PER_SECOND instead, please create a bug report at https://github.com/doudz/homeassistant-myjdownloader/issues```

So i did :)

**Comment by Nyaran** [comment]
Sorry, but I only maintain the card, and that is a bug for the [integration](https://github.com/doudz/homeassistant-myjdownloader).

There is an issue about it: https://github.com/doudz/homeassistant-myjdownloader/issues/41

**Comment by ojaksch** [comment]
Ha! I see...sorry for making noise, but thanks for clarifying!
